/**
 * Copyright 2024 F5, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

'use strict';

const cloneDeep = require('lodash/cloneDeep');
const AS3Properties = require('@automation-toolchain/f5-appsvcs-classic-schema/properties');
const AS3PropertiesAddtnl = require('../../src/lib/AS3/as3PropertiesCustom.json');

const assert = require('../testUtils/assert');
const buildProtectedObj = require('../../src/utils/convert/buildProtectedObj');
const cleanupRD = require('../../src/utils/convert/cleanupRD');
const convertToNameValueObj = require('../../src/utils/convert/convertToNameValueObj');
const declarationBase = require('../../src/utils/convert/declarationBase');
const dedupeArray = require('../../src/utils/convert/dedupeArray');
const deleteProperties = require('../../src/utils/convert/deleteProperties');
const enabledToEnable = require('../../src/utils/convert/enabledToEnable');
const findLocation = require('../../src/utils/convert/findLocation');
const formatStr = require('../../src/utils/convert/formatStr');
const getMergedAS3Properties = require('../../src/converters/as3/properties');
const getObjectType = require('../../src/utils/convert/getObjectType');
const handleObjectRef = require('../../src/utils/convert/handleObjectRef');
const hyphensToCamel = require('../../src/utils/convert/hyphensToCamel');
const isNumber = require('../../src/utils/convert/isNumber');
const prependObjProps = require('../../src/utils/convert/prependObjProps');
const recursiveCamelize = require('../../src/utils/convert/recursiveCamelize');
const renameProperties = require('../../src/utils/convert/renameProperties');
const returnEmptyObjIfNone = require('../../src/utils/convert/returnEmptyObjIfNone');
const unquote = require('../../src/utils/convert/unquote');

describe('Converter utils (util/convert)', () => {
    describe('buildProtectedObject', () => {
        it('should build from a protected property', () => {
            const input = 'f5f5'.toString('base64');
            const output = buildProtectedObj(input);
            const expected = {
                ciphertext: 'ZjVmNQ==',
                protected: 'eyJhbGciOiJkaXIiLCJlbmMiOiJub25lIn0=',
                ignoreChanges: true
            };
            assert.deepStrictEqual(output, expected);
        });

        it('should build from an unprotected property', () => {
            const input = '$M$f5f5enctext'.toString('base64');
            const output = buildProtectedObj(input);
            const expected = {
                ciphertext: 'JE0kZjVmNWVuY3RleHQ=',
                protected: 'eyJhbGciOiJkaXIiLCJlbmMiOiJmNXN2In0=',
                ignoreChanges: true
            };
            assert.deepStrictEqual(output, expected);
        });
    });

    describe('convertToNameValueObj', () => {
        it('should convert a string to object', () => {
            const input = '"foo: bar"';
            const output = convertToNameValueObj(input);
            assert.deepStrictEqual(output, { name: 'foo', value: 'bar' });
        });

        it('should convert an actual value', () => {
            const input = '"ip: IP::remote_addr"';
            const output = convertToNameValueObj(input);
            assert.deepStrictEqual(output, { name: 'ip', value: 'IP::remote_addr' });
        });

        it('should handle an "empty" value', () => {
            const input = 'X-Header-Insert:';
            const output = convertToNameValueObj(input);
            assert.deepStrictEqual(output, { name: 'X-Header-Insert', value: '' });
        });
    });

    describe('declarationBase', () => {
        describe('.AS3', () => {
            it('should return the base json', () => {
                const output = declarationBase.AS3();
                assert.deepStrictEqual(output.class, 'ADC');
                assert.deepStrictEqual(output.label, 'F5 BIG-IP Converted Declaration');
                assert.deepStrictEqual(output.remark, 'Generated by Automation Config Converter');
            });

            it('should optionally add the controls stanza', () => {
                const output = declarationBase.AS3({ controls: true });
                const expected = {
                    class: 'Controls',
                    trace: true,
                    logLevel: 'debug'
                };
                assert.deepStrictEqual(output.controls, expected);
            });
        });

        describe('.DO', () => {
            it('should return the base json', () => {
                const output = declarationBase.DO();
                assert.deepStrictEqual(output.class, 'Device');
                assert.isTrue(output.async);
            });

            it('should optionally add the controls stanza', () => {
                const output = declarationBase.DO({ controls: true });
                assert.deepStrictEqual(output.controls.class, 'Controls');
                assert.include(output.controls.userAgent, 'F5-AUTOMATION-CONFIG-CONVERTER');
                assert.isTrue(output.controls.trace);
                assert.isTrue(output.controls.traceResponse);
                assert.isFalse(output.controls.dryRun);
            });
        });
    });

    describe('dedupeArray', () => {
        it('should remove duplicate strings', () => {
            const input = ['hi', 'test', 'str', 'hi'];
            const output = dedupeArray(input);
            assert.deepStrictEqual(output, ['hi', 'test', 'str']);
        });

        it('should remove duplicate ref objects', () => {
            const input = [{ use: 'test' }, { use: 'another' }, { use: 'test' }];
            const output = dedupeArray(input);
            assert.deepStrictEqual(output, [{ use: 'test' }, { use: 'another' }]);
        });

        it('should handle both simultaneously', () => {
            const input = ['hi', { use: 'test' }, '3', 'hi', { use: 'the' }, { use: 'test' }];
            const output = dedupeArray(input);
            assert.deepStrictEqual(output, ['hi', { use: 'test' }, '3', { use: 'the' }]);
        });
    });

    describe('enabledToEnable', () => {
        it('should handle "enabled"', () => {
            const input = 'enabled';
            const output = enabledToEnable(input);
            assert.deepStrictEqual(output, 'enable');
        });

        it('should handle "disabled"', () => {
            const input = 'disabled';
            const output = enabledToEnable(input);
            assert.deepStrictEqual(output, 'disable');
        });

        it('should not handle anything else', () => {
            const input = 'auto';
            const output = enabledToEnable(input);
            assert.deepStrictEqual(output, 'auto');
        });
    });

    describe('findLocation', () => {
        it('should split the BIG-IP path', () => {
            const input = '/Tenant1/App1/Profile1';
            const output = findLocation(input);
            const expected = {
                app: 'App1',
                iapp: false,
                original: '/Tenant1/App1/Profile1',
                profile: 'Profile1',
                tenant: 'Tenant1'
            };
            assert.deepStrictEqual(output, expected);
        });

        // AS3 supports '.' and '-' in names and pathes since v3.17.1
        it('should save chars ._-', () => {
            const input = '/Te_nan.t1/App-1/Prof.ile1';
            const output = findLocation(input);
            const expected = {
                app: 'App-1',
                iapp: false,
                original: '/Te_nan.t1/App-1/Prof.ile1',
                profile: 'Prof.ile1',
                tenant: 'Te_nan.t1'
            };
            assert.deepStrictEqual(output, expected);
        });
    });

    describe('formatStr', () => {
        it('should trim path to 194 symbols', () => {
            const input = '/AS3_Tenant_longer_than_48wwwwwwwwwwwwwwwwwwwwwwwwww/AS3_Application_longer_than_48wwwwwwwwwwwwwwwwwwwwwwwwww/Profile_name_longer_than_194qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqaaaa';
            const output = formatStr(input);
            assert.deepStrictEqual(
                output,
                '/AS3_Tenant_longer_than_48wwwwwwwwwwwwwwwwwwwwwwwwww/AS3_Application_longer_than_48wwwwwwwwwwwwwwwwwwwwwwwwww/Profile_name_longer_than_194qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq'
            );
        });

        it('should return 3rd element as object name if name not quoted', () => {
            const input = 'ltm vurtual /AS3_Tenant_longer_than_48wwwwwwwwwwwwwwwwwwwwwwwwww/AS3_Application_longer_than_48wwwwwwwwwwwwwwwwwwwwwwwwww/Profile_name_longer_than_194qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqaaaa';
            const output = formatStr(input);
            assert.deepStrictEqual(
                output,
                '/AS3_Tenant_longer_than_48wwwwwwwwwwwwwwwwwwwwwwwwww/AS3_Application_longer_than_48wwwwwwwwwwwwwwwwwwwwwwwwww/Profile_name_longer_than_194qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq'
            );
        });
        it('should replace spaces with _ if profile name quoted', () => {
            const input = 'ltm vurtual "/AS3_Tenant_longer_than_48wwwwwwwwwwwwwwwwwwwwwwwwww/AS3_Application_longer_than_48wwwwwwwwwwwwwwwwwwwwwwwwww/Profile_name_longer_than_194 with spaces qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqaaaa"';
            const output = formatStr(input);
            assert.deepStrictEqual(
                output,
                '/AS3_Tenant_longer_than_48wwwwwwwwwwwwwwwwwwwwwwwwww/AS3_Application_longer_than_48wwwwwwwwwwwwwwwwwwwwwwwwww/Profile_name_longer_than_194_with_spaces_qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq'
            );
        });

        it('should remove leading _', () => {
            const input = 'ltm vurtual "/AS3_Tenant_longer_than_48wwwwwwwwwwwwwwwwwwwwwwwww/AS3_Application_longer_than_48wwwwwwwwwwwwwwwwwwwwwwwwww/_Profile_name_longer_than_194 with spaces qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqaaaa"';
            const output = formatStr(input);
            assert.deepStrictEqual(
                output,
                '/AS3_Tenant_longer_than_48wwwwwwwwwwwwwwwwwwwwwwwww/AS3_Application_longer_than_48wwwwwwwwwwwwwwwwwwwwwwwwww/_Profile_name_longer_than_194_with_spaces_qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq'
            );
        });
    });

    describe('getObjectType', () => {
        it('should return the correct object type', () => {
            const input = { 'ltm profile http /AS3_Tenant/AS3_Application/webtls': {} };
            const output = getObjectType('/AS3_Tenant/AS3_Application/webtls', input);
            assert.deepStrictEqual(output, 'http');
        });

        it('should only work on ltm objects', () => {
            const input = { 'analytics gui-widget /Common/12345678910': {} };
            const output = getObjectType('/Common/12345678910', input);
            assert.isFalse(output);
        });
    });

    describe('handleObjectRef', () => {
        it('should recognize default objects', () => {
            const input = '/Common/http';
            const output = handleObjectRef(input);
            assert.deepStrictEqual(output, { bigip: '/Common/http' });
        });

        it('should handle custom objects', () => {
            const input = '/Common/custom_thing';
            const output = handleObjectRef(input);
            assert.deepStrictEqual(output, { use: '/Common/Shared/custom_thing' });
        });
    });

    describe('hyphensToCamel', () => {
        it('should convert from hyphen-case to camelCase', () => {
            const input = 'example-string-here';
            const output = hyphensToCamel(input);
            assert.deepStrictEqual(output, 'exampleStringHere');
        });
    });

    describe('isNumber', () => {
        const TEST_SET = [
            { isValid: true, input: 12345, name: 'should return true if integer' },
            { isValid: true, input: '12345', name: 'should return true if stringified integer' },
            { isValid: true, input: '12345.0', name: 'should return true if stringified float' },
            { isValid: true, input: '-12345.0', name: 'should return true if stringified float with leadig `-` sign' },
            { isValid: true, input: '+12345.0', name: 'should return true if stringified float with leadig `+` sign' },
            { isValid: true, input: '+12345.0e2', name: 'should return true if stringified float with leadig `+` sign and `e` base' },
            { isValid: true, input: 2 ** 54, name: 'should return true even for big numbers' },
            { isValid: false, input: '1a2b3c', name: 'should return false if true string' },
            { isValid: false, input: NaN, name: 'should return false if NaN' },
            { isValid: false, input: Infinity, name: 'should return false if Infinity' },
            { isValid: false, input: true, name: 'should return false if true' },
            { isValid: false, input: false, name: 'should return false if false' }
        ];

        TEST_SET.forEach((testData) => {
            it(testData.name, () => assert.deepStrictEqual(isNumber(testData.input), testData.isValid));
        });
    });

    describe('prependObjProps', () => {
        it('should work for hsts, but not enforcement', () => {
            const input = {
                includeSubdomains: true,
                period: 7862400,
                insert: false,
                preload: false
            };
            const output = prependObjProps(input, 'hsts');
            const expected = {
                hstsIncludeSubdomains: true,
                hstsPeriod: 7862400,
                hstsInsert: false,
                hstsPreload: false
            };
            assert.deepStrictEqual(output, expected);
        });
    });

    describe('recursiveCamelize', () => {
        it('should convert keys in all included objects to camelCase', () => {
            const input = { 'test-key': { 'test-sub-key': true, 'second.key': false } };
            const output = recursiveCamelize(input);
            const expected = { testKey: { testSubKey: true, 'second.key': false } };
            assert.deepStrictEqual(output, expected);
        });
    });

    describe('returnEmptyObjIfNone', () => {
        it('should return empty if the property is "none"', () => {
            const input = { test: 'none' };
            const output = returnEmptyObjIfNone(input.test, input);
            assert.isEmpty(output);
        });

        it('should otherwise return in original input', () => {
            const input = { test: 'test test' };
            const output = returnEmptyObjIfNone(input.test, input);
            assert.deepStrictEqual(output, input);
        });
    });

    describe('unquote', () => {
        it('should unquote a string', () => {
            const input = '"Test string"';
            const output = unquote(input);
            assert.deepStrictEqual(output, 'Test string');
        });

        it('should unquote a single-quote string', () => {
            const input = "'Test string'";
            const output = unquote(input);
            assert.deepStrictEqual(output, 'Test string');
        });

        it('should unquote a tilde-quote string', () => {
            const input = '`Test string`';
            const output = unquote(input);
            assert.deepStrictEqual(output, 'Test string');
        });

        it('should not remove other characters', () => {
            const input = 'Test string';
            const output = unquote(input);
            assert.deepStrictEqual(output, 'Test string');
        });
    });

    describe('Merging recognized properties (as3Properties.js)', () => {
        let originAS3Props;
        let originAS3AddtnlProps;

        before(() => {
            originAS3Props = cloneDeep(AS3Properties);
            originAS3AddtnlProps = cloneDeep(AS3PropertiesAddtnl);
        });

        afterEach(() => {
            assert.deepStrictEqual(AS3Properties, originAS3Props, 'should not modify original data');
            assert.deepStrictEqual(AS3PropertiesAddtnl, originAS3AddtnlProps, 'should not modify original data');
        });

        it('Should merge properties.json with as3PropertiesCustom.json', () => {
            const mergedAS3Properties = getMergedAS3Properties();

            let key = 'ltm monitor udp';
            assert.isDefined(originAS3AddtnlProps[key], 'should be defined in AS3 custom properties');
            assert.isUndefined(originAS3Props[key], 'should not be defined in AS3 properties');
            assert.isDefined(mergedAS3Properties[key], 'should be defined in merged properties');

            key = 'ltm pool';
            assert.isUndefined(originAS3AddtnlProps[key], 'should not be defined in AS3 custom properties');
            assert.isDefined(originAS3Props[key], 'should be defined in AS3 properties');
            assert.isDefined(mergedAS3Properties[key], 'should be defined in merged properties');

            assert.notDeepEqual(mergedAS3Properties, originAS3Props, 'should not modify original properties');
            assert.notDeepEqual(mergedAS3Properties, originAS3AddtnlProps, 'should not modify original properties');
        });
    });

    describe('Delete property by path (deleteProperties.js)', () => {
        it('should delete properties', () => {
            const input = { a: [{ key: 'true' }, { key2: 'false' }], b: 10 };
            const property = '/a/1/key2';
            const results = deleteProperties(input, [property]);
            assert.deepStrictEqual(input, { a: [{ key: 'true' }], b: 10 });
            assert.deepStrictEqual(results.ignored, []);
            assert.sameDeepMembers(results.deleted, [property, '/a/1']);
        });

        it('should delete properties and clean up empty objects', () => {
            const input = { a: [{ key: 'true' }], b: 10 };
            const property = '/a/0';
            const results = deleteProperties(input, [property]);
            assert.deepStrictEqual(input, { b: 10 });
            assert.deepStrictEqual(results.ignored, []);
            assert.sameDeepMembers(results.deleted, [property, '/a']);
        });

        it('should delete properties and clean up difficult objects', () => {
            const input = { a: 'testA', b: { b_1: { value: 'test_value' }, b_2: { value: 'test_value' } } };
            const property1 = '/b/b_1/value';
            const property2 = '/b/b_2/value';
            const results = deleteProperties(input, [property1, property2]);
            assert.deepStrictEqual(input, { a: 'testA' });
            assert.deepStrictEqual(results.ignored, []);
            assert.sameDeepMembers(results.deleted, [
                property1,
                property2,
                '/b',
                '/b/b_1',
                '/b/b_2'
            ]);
        });

        it('should delete properties and clean up difficult empty objects', () => {
            const input = { a: { t1: [{ key: 'true' }], t2: 11 }, b: 10 };
            const property1 = '/a/t1/0/key';
            const property2 = '/a/t1/0';
            const results1 = deleteProperties(input, [property1, property2]);
            assert.deepStrictEqual(input, { a: { t2: 11 }, b: 10 });
            // try again to delete already removed key
            const results2 = deleteProperties(input, [property1, property2]);
            assert.deepStrictEqual(input, { a: { t2: 11 }, b: 10 });
            assert.deepStrictEqual(results1.ignored, []);
            assert.sameDeepMembers(results1.deleted, [
                property1,
                property2,
                '/a/t1'
            ]);
            assert.sameDeepMembers(results2.ignored, [property1, property2]);
            assert.deepStrictEqual(results2.deleted, []);
        });

        it('should ignore invalid paths', () => {
            const input = { a: [{ key: 'true' }, { key2: 'false' }], b: 10 };
            const property = '/a/1/key2';
            const results = deleteProperties(input, [
                property,
                'invalidProperty',
                'invalidProperty/',
                '/',
                '/     ',
                '   /     '
            ]);
            assert.deepStrictEqual(input, { a: [{ key: 'true' }], b: 10 });
            assert.sameDeepMembers(results.ignored, [
                'invalidProperty',
                'invalidProperty/',
                '/',
                '/     ',
                '   /     '
            ]);
            assert.sameDeepMembers(results.deleted, [property, '/a/1']);
        });

        it('should remove all objects', () => {
            const input = { a: [{ key: 'true' }], b: 10 };
            const results = deleteProperties(input, [
                '/a/0/key',
                '/b'
            ]);
            assert.deepStrictEqual(input, {});
            assert.sameDeepMembers(results.ignored, []);
            assert.sameDeepMembers(results.deleted, [
                '/a/0/key',
                '/a/0',
                '/a',
                '/b'
            ]);
        });

        it('should remove array elemets in different order', () => {
            let input = [0, 1, 2, 3];
            let results = deleteProperties(input, [
                '/0',
                '/1',
                '/2',
                '/3'
            ]);
            assert.deepStrictEqual(input, []);
            assert.sameDeepMembers(results.ignored, []);
            assert.sameDeepMembers(results.deleted, [
                '/0',
                '/1',
                '/2',
                '/3'
            ]);

            input = [0, 1, 2, 3];
            results = deleteProperties(input, [
                '/3',
                '/2',
                '/1',
                '/0'
            ]);
            assert.deepStrictEqual(input, []);
            assert.sameDeepMembers(results.ignored, []);
            assert.sameDeepMembers(results.deleted, [
                '/0',
                '/1',
                '/2',
                '/3'
            ]);

            input = [0, 1, 2, 3];
            results = deleteProperties(input, [
                '/3',
                '/0',
                '/1',
                '/2'
            ]);
            assert.deepStrictEqual(input, []);
            assert.sameDeepMembers(results.ignored, []);
            assert.sameDeepMembers(results.deleted, [
                '/0',
                '/1',
                '/2',
                '/3'
            ]);

            input = [0, 1, 2, 3];
            results = deleteProperties(input, [
                '/0',
                '/2'
            ]);
            assert.deepStrictEqual(input, [1, 3]);
            assert.sameDeepMembers(results.ignored, []);
            assert.sameDeepMembers(results.deleted, [
                '/0',
                '/2'
            ]);
        });

        it('should cleanup parent objects correctly', () => {
            let input = { a: [0, { b: 10 }, 2, { c: 20 }] };
            let results = deleteProperties(input, ['/a/1/b', '/a/0', '/a/3/c', '/a/2']);

            assert.deepStrictEqual(input, {});
            assert.sameDeepMembers(results.ignored, []);
            assert.sameDeepMembers(results.deleted, [
                '/a',
                '/a/0',
                '/a/1',
                '/a/1/b',
                '/a/2',
                '/a/3',
                '/a/3/c'
            ]);

            input = { a: [0, { b: 10 }, 2, { c: [0, [{ d: 10 }]] }] };
            results = deleteProperties(input, ['/a/1/b', '/a/0', '/a/3/c/1/0/d']);
            assert.deepStrictEqual(input, { a: [2, { c: [0] }] });
            assert.sameDeepMembers(results.ignored, []);
            assert.sameDeepMembers(results.deleted, [
                '/a/0',
                '/a/1',
                '/a/1/b',
                '/a/3/c/1',
                '/a/3/c/1/0',
                '/a/3/c/1/0/d'
            ]);
        });

        it('should not touch origin empty objects', () => {
            const input = {
                a: [{}], b: [], c: [], d: {}
            };
            const results = deleteProperties(input, [
                '/a/0/key',
                '/b/1'
            ]);
            assert.deepStrictEqual(
                input,
                {
                    a: [{}], b: [], c: [], d: {}
                }
            );
            assert.sameDeepMembers(results.ignored, [
                '/a/0/key',
                '/b/1'
            ]);
            assert.sameDeepMembers(results.deleted, []);
        });
    });

    describe('Delete route domain suffixies from object (cleanupRD.js)', () => {
        it('should delete RD ip suffixes', () => {
            const input = { serverAddresses: ['10.10.124.100%47', '10.10.34.102', '2001:db8::32%47', '2001:db8::7', '2001:db8::7%47/64'] };
            const output = cleanupRD(input);
            const expected = { serverAddresses: ['10.10.124.100', '10.10.34.102', '2001:db8::32', '2001:db8::7', '2001:db8::7/64'] };
            assert.deepStrictEqual(output, expected);
        });
    });

    describe('Rename properties (renameProperties.js)', () => {
        it('should rename properties', () => {
            const originObj = {
                renameMe: [
                    {
                        renameMe: true
                    }
                ],
                b: {
                    renameMe: true
                }
            };
            const renamed = renameProperties(originObj, (parent, key, value) => {
                if (key === 'renameMe' && (
                    typeof value === 'object' || value === true)) {
                    return 'renamed';
                }
                return key;
            });

            assert.deepStrictEqual(originObj, {
                renamed: [
                    {
                        renamed: true
                    }
                ],
                b: {
                    renamed: true
                }
            }, 'should renamed properties');

            assert.sameDeepMembers(renamed, [
                [['renameMe'], ['renamed']],
                [['renameMe', 0, 'renameMe'], ['renamed', 0, 'renamed']],
                [['b', 'renameMe'], ['b', 'renamed']]
            ], 'should keep track of origin and renamed paths');
        });
    });
});
