/**
 * Copyright 2024 F5, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* eslint-disable @typescript-eslint/no-require-imports */
const { v4: uuid } = require('uuid') as { v4: () => string };

const adcSchema = require('../vendor/f5-appsvcs-classic-schema/schema/latest/adc-schema.json') as {
    properties: { schemaVersion: { anyOf: Array<{ const?: string }> } }
};

const { name, version } = require('../../package.json') as { name: string; version: string };

export interface AS3Config {
    next?: boolean;
    controls?: boolean;
}

export interface DOConfig {
    controls?: boolean;
}

export interface AS3Declaration {
    class: 'ADC';
    schemaVersion: string;
    id: string;
    label: string;
    remark: string;
    controls?: {
        class: 'Controls';
        trace: boolean;
        logLevel: string;
    };
    [key: string]: unknown;
}

export interface DODeclaration {
    schemaVersion: string;
    class: 'Device';
    async: boolean;
    Common: {
        class: 'Tenant';
    };
    controls?: {
        class: 'Controls';
        userAgent: string;
        trace: boolean;
        traceResponse: boolean;
        dryRun: boolean;
    };
    [key: string]: unknown;
}

const declarationBase = {
    AS3: (config?: AS3Config): AS3Declaration => {
        // config may be empty
        const next = config?.next;

        const declaration: AS3Declaration = {
            class: 'ADC',
            schemaVersion: adcSchema.properties.schemaVersion.anyOf[1]?.const ?? '3.52.0',
            id: `urn:uuid:${uuid()}`,
            label: next ? 'F5 BIG-IP Next Converted Declaration' : 'F5 BIG-IP Converted Declaration',
            remark: 'Generated by Automation Config Converter'
        };

        if (config?.controls) {
            declaration.controls = {
                class: 'Controls',
                trace: true,
                logLevel: 'debug'
            };
        }

        return declaration;
    },

    DO: (config?: DOConfig): DODeclaration => {
        const declaration: DODeclaration = {
            schemaVersion: '1.0.0',
            class: 'Device',
            async: true,
            Common: {
                class: 'Tenant'
            }
        };

        if (config?.controls) {
            declaration.controls = {
                class: 'Controls',
                userAgent: `${name.toUpperCase()}/${version}`,
                trace: true,
                traceResponse: true,
                dryRun: false
            };
        }

        return declaration;
    }
};

export default declarationBase;
module.exports = declarationBase;
